### ISSUE TITLE
Cover images not loading in uToken page

### ISSUE THREAD

**Issue by leia-collection** [0xLeia/unicly-utoken-info#2]
See this uToken page:

https://app.unic.ly/#/utoken-contract/0x4eee9e9c2a4f0a731b54e5766b8e7f21c2e2960c

The cover images for all NFTs do not load for some reason. If you click on any of them, they show up ok. As you can see, all images are NFTs originally from OpenSea.io - [example after click](https://app.unic.ly/#/utoken-item/0x4eee9e9c2a4f0a731b54e5766b8e7f21c2e2960c/0) - [example in opensea](https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/10240480389665596352076890820103950210745044151223870890732951955322234208257)

**Comment by 0xLeia** [comment]
We identified this issue as well and we're fixing it soon! Thank you.
